#!/bin/sh
# Copyright (C) 2016 Velocloud Inc

# Load hotplug common utilities
. /etc/modemmanager/25-modemmanager-common

# We require a interface name
[ -n "${INTERFACE}" ] || return

# If blacklisted by VID:PID, ignore 'add' event
[ "${ACTION}" == "add" ] && {
	local BLACKLIST_REASON=$(mm_check_modemmanager_blacklist /sys${DEVPATH})
	[ -n "${BLACKLIST_REASON}" ] && {
		mm_log "${ACTION} network interface ${INTERFACE}: event ignored: ${BLACKLIST_REASON}"
		return
	}
}

# Report network interface
mm_log "${ACTION} network interface ${INTERFACE}: event processed"
mm_report_event "${ACTION}" "${INTERFACE}" "net"

# Look for an associated cdc-wdm interface
{
	local cdcwdm

	case "${ACTION}" in
		"add")	  cdcwdm=$(mm_track_cdcwdm "${INTERFACE}") ;;
		"remove") cdcwdm=$(mm_untrack_cdcwdm "${INTERFACE}") ;;
	esac

	# Report cdc-wdm device, if any
	[ -n "${cdcwdm}" ] && {
		mm_log "${ACTION} cdc interface ${cdcwdm}: custom event processed"
		mm_report_event "${ACTION}" "${cdcwdm}" "usbmisc"
	}
}
