#!/bin/sh
# Copyright (C) 2016 Velocloud Inc

# Load hotplug common utilities
. /etc/modemmanager/25-modemmanager-common

# We require a device name
[ -n "$DEVNAME" ] || return

# If blacklisted by VID:PID, ignore 'add' event
[ "${ACTION}" == "add" ] && {
	local BLACKLIST_REASON=$(mm_check_modemmanager_blacklist /sys${DEVPATH})
	[ -n "${BLACKLIST_REASON}" ] && {
		mm_log "${ACTION} serial interface ${DEVNAME}: event ignored: ${BLACKLIST_REASON}"
		return
	}
}

# Report TTY
mm_log "${ACTION} serial interface ${DEVNAME}: event processed"
mm_report_event "${ACTION}" "${DEVNAME}" "tty"
